feat/add coredump debugging script
deep-observability-lab/gdb-scripts pull request #4
Opened 2024-11-23 07:28 UTC by zahra121281

2024-11-23 15:18 UTC, azharivs requested changes

2024-11-23 15:18 UTC, azharivs commented on gdb_automate.py
> +        print(f"Error running readelf: {e}")
please remove fstring!

2024-11-23 15:18 UTC, azharivs commented on gdb_automate.py
> +            print(f"  - {lib}")
fstring!

2024-11-23 15:18 UTC, azharivs commented on gdb_commands/end_command.py
> +            print(f"Error fetching details from target: {e}")
fstring!

2024-11-23 15:18 UTC, azharivs commented on gdb_automate.py
> +        print("bellow libraries don't found in the workspace." )
Grammar correction:

"Following libraries were not found in workspace."

2024-11-23 15:18 UTC, azharivs commented on gdb_automate.py
> +    if len(not_found ) > 0 :
remove extra space before )

2024-11-23 15:18 UTC, azharivs commented on gdb_automate.py
> +        cont = input("1- continue with this libraries at workspace\n"
Please enter one option:\n
[1] Continue with whatever libraries found in workspace

2024-11-23 15:18 UTC, azharivs commented on gdb_automate.py
> +             "2- use libraries in default path in local system.\n"
where is the default path? Can you also print it here?

2024-11-23 15:18 UTC, azharivs commented on gdb_automate.py
> +            print("Exiting the program.")
"Exiting" is enough

2024-11-23 15:18 UTC, azharivs commented on gdb_commands/bins.py
> +
there is no need for empty line here, the PrettyPrinter is part of the loop block

2024-11-23 15:18 UTC, azharivs commented on gdb_commands/end_command.py
> +                print("detach from the process " )
extra space before )

2024-11-23 15:18 UTC, azharivs commented on gdb_commands/end_command.py
> +                    gdbserver_command = 'pkill gdbserver'.format(self.password)
there should be a placeholder {} for self.password!!

2024-11-23 15:18 UTC, azharivs commented on gdb_commands/end_command.py
> +                print( "killing gdbserver process on remote...")
extra space after (

2024-11-23 15:18 UTC, azharivs commented on gdb_commands/heap.py
> +            value = self.read_memory(cur , num_words)
extra space before ,

2024-11-23 15:18 UTC, azharivs commented on gdb_commands/heap.py
> +
one empty line is enough

2024-11-23 15:18 UTC, azharivs commented on gdb_commands/process.py
> +                return "not supported in coredump debugging" , "not supported in coredump debugging"
I would do something like:

                print("not supported in coredump debugging")
                return None , None

2024-11-23 15:18 UTC, azharivs commented on gdb_coredump.py
> +    parser.add_argument('-a', '--architecture', type=str, required=True,
why don't you set the default value right here and not later in the code?
Also provide a few examples in help to show the options for --architecture. A better way is to select from a predefined list of choises as explained in this example:

https://docs.python.org/2/library/argparse.html#choices

2024-11-23 15:18 UTC, azharivs commented on setup_local.py
> +    def install_gnome_terminal(self):
The only change you did are four whitespaces at the end of the line. It is time to install a good python code style plugin so you can auto detect these mistakes.

2024-11-25 08:41 UTC, zahra121281 commented on gdb_automate.py
> +        print(f"Error running readelf: {e}")
removed

2024-11-25 10:23 UTC, merged