Fb launch json generator
deep-observability-lab/gdb-scripts pull request #5
Opened 2024-12-10 18:52 UTC by zahra121281

2024-12-15 15:44 UTC, azharivs commented
Since the number of required python packages are increasing, please add a dependency section to your readme file with instructions on how to install the needed python modules such as ssh-utils, etc.

2024-12-15 15:55 UTC, azharivs requested changes
Please find my comments, thank you!

2024-12-15 15:55 UTC, azharivs commented on README.md
> +bashsudo python3 gdb_remote.py [-h] -i IP -u USERNAME -pid PROCESS_ID [-a ARCHITECTURE]
you need to insert a new line between bash and sudo

2024-12-15 15:55 UTC, azharivs commented on gdb_automate.py
> +        if not os.path.exists(target_path):
what if you have overwritten 'core_file' with a newer version of the file but the target_path is still pointing to an older version of the core file that got copied there as a result of a previous invocation of the gdb_remote.py on the older core file? I think you should always use the fresh core file from where the user is pointing to it.

2024-12-15 15:55 UTC, azharivs commented on gdb_automate.py
> +                gdb_script=tmp_file.name
why not strip the \n here?

2024-12-15 15:55 UTC, azharivs commented on gdb_coredump.py
> +                        help='Direct path for coredump file.')
what do you mean by a "Direct path"? Absolute? Relative?

2024-12-15 15:55 UTC, azharivs commented on gdb_remote.py
> +    parser.add_argument('-ui', '--user_interface', type=str, required=True,
Better if you set a default 'gdb' for this?

2024-12-16 06:34 UTC, zahra121281 commented on gdb_coredump.py
> +                        help='Direct path for coredump file.')
Absolute , edited

2024-12-30 09:49 UTC, merged